# Generated by Django 3.2.5 on 2021-07-24 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Тема')),
                ('text', models.TextField(verbose_name='Текст формы')),
            ],
            options={
                'verbose_name': 'Форма помощи',
                'verbose_name_plural': 'Формы помощи',
            },
        ),
        migrations.CreateModel(
            name='TeleSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=200, verbose_name='Токен')),
                ('chat_id', models.CharField(max_length=200, verbose_name='чат id')),
                ('text', models.TextField(verbose_name='Текст отправки')),
            ],
            options={
                'verbose_name': 'Настройку',
                'verbose_name_plural': 'Настройки',
            },
        ),
    ]
