# Generated by Django 3.2.5 on 2021-07-24 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_course', models.CharField(max_length=50, unique=True, verbose_name='Название курса')),
                ('slug_course', models.SlugField(max_length=200, unique=True, verbose_name='URL')),
                ('name_subject', models.CharField(max_length=50, verbose_name='Пердмет')),
                ('short_description', models.CharField(max_length=200, verbose_name='Короткое описание')),
                ('long_description', models.TextField(verbose_name='Длинное описание')),
                ('image_course', models.ImageField(upload_to='', verbose_name='Картинка курса')),
                ('pub_date', models.DateField(verbose_name='Дата начала')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Тип',
                'verbose_name_plural': 'Типы',
            },
        ),
        migrations.CreateModel(
            name='BaseForArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_rus', models.CharField(max_length=50, unique=True, verbose_name='Название на рус')),
                ('slug_article', models.SlugField(max_length=200, unique=True, verbose_name='URL')),
                ('short_description', models.CharField(max_length=200, verbose_name='Короткое описание')),
                ('long_description', models.TextField(verbose_name='Длинное описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Картинка месяца')),
                ('pub_date', models.DateField(verbose_name='Дата начала')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bind_course_set', to='courses.course', verbose_name='Курс')),
                ('type_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='type_model_set', to='courses.type', verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
            },
        ),
    ]
