# Generated by Django 3.2.5 on 2021-07-24 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(default=1, verbose_name='Номер домашнего задания')),
                ('pdf_file_for_student', models.FileField(blank=True, null=True, upload_to='', verbose_name='Домашнее задание без решения')),
                ('pdf_file_for_teacher', models.FileField(blank=True, null=True, upload_to='', verbose_name='Домашнее задание с решением')),
                ('pub_date_for_student', models.DateTimeField(verbose_name='Дата публикации без решения')),
                ('pub_date_for_teacher', models.DateTimeField(verbose_name='Дата публикации с решением')),
                ('deadline', models.DateTimeField(verbose_name='Дедлайн')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bind_month_set', to='courses.baseforarticle', verbose_name='Месяц')),
            ],
            options={
                'verbose_name': 'Домашнее задание',
                'verbose_name_plural': 'Домашние задания',
            },
        ),
    ]
